osx_image: xcode9.4
language: objective-c

cache:
  - bundler
  - cocoapods

before_install:
  - bundle update  
  - bundle exec pod repo update

script:
  - travis_wait 50 bundle exec fastlane lint_pods
