[tool.towncrier]
name = "Changes in"
filename = "CHANGES.rst"
directory = "changelog.d"
template = "changelog.d/_template.md.jinja"

[[tool.towncrier.type]]
    directory = "feature"
    name = "✨ Features"
    showcontent = true

[[tool.towncrier.type]]
    directory = "bugfix"
    name = "🐛 Bugfixes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "build"
    name = "🧱 Build"
    showcontent = true
